<?xml version="1.0"?>
<!DOCTYPE stock [
    <!ELEMENT stock (new-car|used-car)*>
    <!ELEMENT new-car (model,price)>
    <!ELEMENT used-car (model,price,mileage,condition?)>
    <!ELEMENT model (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT mileage (#PCDATA)>
    <!ELEMENT condition (#PCDATA)>
]>

<stock>
    <new-car>
        <model>model1</model>
        <price>100000</price>
    </new-car>
    <used-car>
        <model>model2</model>
        <price>5555555</price>
        <mileage>15</mileage>
        <condition>bad</condition>
    </used-car>
    <used-car>
        <model>model4</model>
        <price>11142</price>
        <mileage>5</mileage>
    </used-car>
    <new-car>
        <model>model3</model>
        <price>22222</price>
    </new-car>
</stock>